### ISSUE TITLE
Where to put moduleMutations()?

### ISSUE THREAD

**Issue by ryanmclaughlin** [posva/vuexfire#10]
I'm testing the new modules update and am having some trouble.

**EDIT:** I think I may be misunderstanding how vuexfire works with mutations. Does it automagically make them for us?

I'm getting the error: 
![image](https://cloud.githubusercontent.com/assets/451112/20453333/b012638c-add5-11e6-8998-6e590c79acb2.png)

Here's the lay of the land:

**/vuex/modules/auth/actions.js**
```
import firebase from '../../../services/firebase.js'

import { AUTHENTICATE } from './mutation-types';

export function fetchUser ({ commit }) {
  return firebase.auth.onAuthStateChanged((user) => {
    commit(AUTHENTICATE, user);
  });
}
```

**/vuex/modules/auth/getters.js**
`export const getAuth = state => state.user`

**/vuex/modules/auth/index.js**
```
import * as actions from './actions';
import * as getters from './getters';

import { AUTHENTICATE } from './mutation-types'

const initialState = {
  user: null
}

const mutations = {
  [AUTHENTICATE] (state, user) {
    state.user = user
  },
}

export default {
  state: { ...initialState },
  actions,
  getters,
  mutations,
}
```

**/vuex/modules/auth/mutation-types.js**
`export const AUTHENTICATE = 'auth/AUTHENTICATE';`

**/vuex/modules/store.js**
```
import Vue from 'vue'
import Vuex from 'vuex'
import VuexFire from 'vuexfire'

import auth from './modules/auth'
import games from './modules/games'

Vue.use(Vuex)
Vue.use(VuexFire)

const debug = process.env.NODE_ENV !== 'production'

export default new Vuex.Store({
  modules: {
    auth,
    games,
  },
  strict: debug,
})
```

**App.vue**
```
  export default {
    components: {
      AppNav
    },
    created () {
      this.$store.dispatch('fetchGames');
      this.$store.dispatch('fetchUser');
    }
  }
```

The only thing I'm able to find is that with I'm supposed to use `mutations: VuexFire.moduleMutations('items')` somewhere if I'm using modules, and I'm not sure where though in a setup like this.

**Comment by posva** [comment]
oh damn, I thought it was clear on the readme 😢 What wasn't clear for you? https://github.com/posva/vuexfire#modules

Vuexfire does not add mutations for you in vuex 2, it does in vuex 1. You have to add mutations yourself. In your case it would be something like this:

```js
// Import the moduleMutations function
import { moduleMutations } from 'vuexfire'
```

```js
// Add them on the mutations object
const mutations = {
  [AUTHENTICATE] (state, user) {
    state.user = user
  },
  ...moduleMutations('auth'),
}
```

If you want to keep your mutations object intact
```js
// OR when exporting the module
export default {
  state: { ...initialState },
  actions,
  getters,
  mutations: {
      ...mutations,
      ...moduleMutations('auth'),
  },
}
```

The name `moduleMutations` may change in the future (until v1 is released). I was thinking about something like `mapMutations` and replace the `mutations` object (when no module) and the method `moduleMutations` (with modules) altogether.

**Comment by ryanmclaughlin** [comment]
Thanks @posva I'll give this a go. I probably didn't understand it because it wasn't spelled out how you did here :) Is it okay to say I'm a visual learner?

**Comment by posva** [comment]
you're welcome
you only have to install the plugin once.
I'll see if I can update the Readme to make the example more clear
