### ISSUE TITLE
Allow listening to error callback

### ISSUE THREAD

**Issue by alex88** [posva/vuexfire#102]
Is there a way to listen for `failureCallbackOrContext` function when binding to a reference?

Maybe add an `errorCallback` as the same as `readyCallback` which seems to be implemented here https://github.com/posva/vuexfire/blob/d041193beca9fbc82262230bf8a82c6a9e4082ab/src/index.js#L166-L168 ?

**Comment by posva** [comment]
there's currently no way of doing so, but it should be easy to add if you want to give it a try 🙂 . If you do, please, add the test as well

**Comment by alex88** [comment]
Yeah I already had in idea about the code, but tests are more difficult 🤕

**Comment by posva** [comment]
In that case, just push the PR, the tests may be a bit too difficult indeed. I'd need to use a real firebase db instead of a mock

**Comment by alex88** [comment]
And configure the db to fail to test the failure callback, I'll do a PR later today

**Comment by alex88** [comment]
Sorry maybe it's better to close it via the PR
