### ISSUE TITLE
Force everything to be an object

### ISSUE THREAD

**Issue by dsl101** [posva/vuexfire#104]
I have a data structure in the store like this:

	const state = {
	  event: {}
	}

which is then bound to a firebase reference `/events/<key>` like this:

![image](https://user-images.githubusercontent.com/900542/29370884-a4fc6422-829e-11e7-9185-06d2e58bb60b.png)

When I `console.log(state.event.pages)`, I get this:

    (2) [undefined × 1, Object, __ob__: Observer]

If I then add a new page with a non-numeric key (say, `a`), I get this:

	Object {__ob__: Observer}
	  1: (...)
	  a: (...)

Lodash functions like `mapKeys()`, `size()` and so on all fail in the first case. What I _really_ want (since the keys can be either numeric or alphas) is to force all the children of `event` to be objects, even if they are numeric keys. Is there a way to ensure this happens?

**Comment by posva** [comment]
No, there's no way of making it look like an object. It looks like Firebase is giving you an array because you're using numerical indexes. vuexfire is not even touching it.
You'll have to ask for help to Firebase guys, I imagine they'll tell you not to use numerical indexes 😕
