### ISSUE TITLE
Option to set ['.key'] property name

### ISSUE THREAD

**Issue by jamesAtcodeninja** [posva/vuexfire#105]
First of all thanks for the great project, it's been a life saver.

Would it be possible to pass in an option to set the property name for ['.key'] in `vuexfire/src/utils/firebase.js` ?

I've been using another property name in a similar fashion prior to using this project and having this feature would make life a whole lot easier.

**Comment by posva** [comment]
I'm glad it's helpful 🙂 
Yeah, this is feasible
What is the need behind this? Other than convenience? I really try to keep the lib very small, I'm unsure about adding this just for convenience

**Comment by jamesAtcodeninja** [comment]
Technically isn't every improvement a means for convenience 😅.

Personally, I've been using `id` because it is the property name of the objects retrieved from my SQL database, and having to rely on `[.key]` would mean my functions will have to check for both `id` or `[.key]`. 
Giving the option to specify the property name would allow your module to be more easily integrated into already-existing projects since there is no naming standard as of yet.

**Comment by posva** [comment]
> Technically isn't every improvement a means for convenience 😅.

Well, not always 😅 . In this specific case, I'd like to see a case when using `.key` is blocking **or** a great improvement by using something else than `.key`

**Comment by jamesAtcodeninja** [comment]
You're right, I can't really think of any other reason than the ones provided - but in regards to the earlier statement, I find that higher-level languages + libraries are made to make it easier for the developer to develop. You can technically do everything by writing in binary 😅. 
Putting that aside, I completely understand if it's something you don't feel the need to invest in. Thanks again.

**Comment by virtuecoder** [comment]
It's a matter of values. In my opinion freedom, in a sense of reducing coupling between the library and the client code and not forcing people on how they write their code, is more important than a small size increase of the library :-)

**Comment by virtuecoder** [comment]
Here is a real life example of '.key' clunkiness. If you want to save an array of items back to firebase you need to remove '.key' property from them. If it was a valid JS identifier, e.g. _key then you could do it nicely using es6 syntax:
`a.forEach(({_key, ...rest}) => ref.child(_key).set(rest))`
but it does not work when you replace _key with '.key'

**Comment by posva** [comment]
@virtuecoder That won't be a problem in the future because `.key` will become not enumerable

**Comment by virtuecoder** [comment]
That would solve only `...` part of the deconstruktor, to skip `'key`, but still you would not be able to deconstruct the `.key` in  `{.key, ...rest}`

**Comment by posva** [comment]
You can do

```js
let {'.key': key, ...rest } = object
```

**Comment by kanethal** [comment]
I feel like I'm not able to access the ['.key'] for my entries... is there a circumstance where this is known to occur?
Now that I'm looking at it, it looks like the .key property is present on the root bound reference, but not for its children properties... Does that mean if we need access to .key for child references we need to bind them to their own state property?
```
{
   family : { //Root reference, has a .key property in addition to the object properties
      .key : (...),
      kids : [ //Array, no .key .value designations, just the representative collection
          {...},
          {...}
       ]
   }
}

**Comment by jamesAtcodeninja** [comment]
The [‘.key’] property is only available for the root node of the bind. In your instance it’s solely the family node.

**Comment by kanethal** [comment]
Great, thanks for the clarification.

**Comment by posva** [comment]
Moved to https://github.com/vuejs/vuefire/issues/129
