### ISSUE TITLE
how to pass non-root state property to bindFirebaseRef

### ISSUE THREAD

**Issue by codeofsumit** [posva/vuexfire#109]
`bindFirebaseRef('todos', ref)` binds to `state.todos`.
How to bind to `state.anotherObj.todos`?

This is especially useful / necessary to bind specific todos, like:
```js
const id = 'abc';
Vue.set(state.todos, id, {});
bindFirebaseRef('todos.' + id, ref)
```

something like `anotherObj.todos` doesn't work. Any other way to do it?

**Comment by posva** [comment]
You cannot, at least for the moment. It's something I may consider in the future. For the moment, you have to create a module to nest things
