### ISSUE TITLE
Is it necessary for unbindFirebaseRef to throw an error?

### ISSUE THREAD

**Issue by dsl101** [posva/vuexfire#111]
Sometimes I just want to call `unbindFirebaseRef()` as a belt & braces approach before binding a store property to a new firebase ref. Could this function simply return a value to indicate success or failure, rather than throw an error? That way I can cleanly ignore it if I don't care, rather than have to `try / catch` or `.catch()`

**Comment by posva** [comment]
you don't need to unbind when binding new values, vuexfire does the unbind for you already 😄 
I think having an error prevents you from trying to unbind in cases you shouldn't
FYI, using a try/catch is not a dirty hack, it sometimes feels like that to me too, but I prefer to keep it explicit here for the moment
