### ISSUE TITLE
should unbindFirebaseRef clear the previously bound state?

### ISSUE THREAD

**Issue by chrisbraddock** [posva/vuexfire#114]
Hi @posva!

I made an assumption that state for a previously bound reference via `bindFirebaseRef` would be cleared when I did a corresponding `unbindFirebaseRef`, but that doesn't seem to be the case. The state does become unbound and no longer reacts to Firebase modifications, but the state still hangs around in the `store`.

Is your recommended approach to `commit` a mutation within the action that performs `unbindFirebaseRef` to clear out the bound state if the `unbindFirebaseRef` succeeds or am I misunderstanding things altogether?

**Comment by posva** [comment]
I left it on purpose in case you need to use it. Of course, you can commit a mutation if you want to clear it, that would be how I would do it 🙂 (I don't really see any other option)
