### ISSUE TITLE
Firebase introduces Cloud Firestore

### ISSUE THREAD

**Issue by shongololo** [posva/vuexfire#117]
Firebase has released [Cloud Firestore](https://firebase.google.com/docs/firestore/rtdb-vs-firestore) which looks to be a significant improvement over the current Realtime Database.

Hopefully, this can be incorporated into Vuexfire?

Related issue at vuejs/vuefire#131

**Comment by posva** [comment]
yes, it's something I'll look into and see how to add it

**Comment by llavre** [comment]
Is there any news about firestore integration in to vuexfire?

**Comment by posva** [comment]
Hello, the truth is I got most working a month ago with vuefire but due to personal matters, I couldn't push it forward. I'll get a release for both, vuefire and vuexfire, before 2018 for sure 🙂 
The first version will not be complete because firestore has more features, for example, you can add a reference to another document (and I think also collection) inside of a document. This is something I want to add without impacting people not using refs

**Comment by bmass02** [comment]
@posva Would you mind making a branch with those changes? I had started integrating Firestore into vuexfire for my personal use, but ran into some issues with the npm package used for testing not up to date with the Firestore Reference docs. Also, I would like to start testing out the new feature.

**Comment by posva** [comment]
It's something I'll add as soon as I can. I don't understand the _not up to date with the Firestore Rference docs_. They look fine to me

**Comment by posva** [comment]
Oh, if you want to check some existing code you can already check the [firestore branch of vuefire ](https://github.com/vuejs/vuefire/tree/firestore)

**Comment by posva** [comment]
Hello! I ended up working a lot on vuefire before releasing a working version for vuexfire that's why it took so long, good news are it has almost all the features I wanted to add. I just released an alpha version, it supports [everything the alpha version of vuefire supports](https://github.com/vuejs/vuefire/issues/145)

If you want to try [v3.0.0-alpha.0](https://github.com/posva/vuexfire/releases/tag/3.0.0-alpha.0) you can install it with the `next` tag: `npm i vuexfire@next`. I will really like to have some testers 🙂 
The API didn't change but it now only works with firestore, you can find some examples in the _examples_ folder just in case.

**Comment by aspben** [comment]
I modified the demo fiddle to use firestore for those interested : https://jsfiddle.net/c4m4c940/

It's working! 

Let me know if there is unnecessary code. Or beginner mistake. Only way i got firestore working was by adding another script tag pointing to firestore.

Thank for making this. I will use it in my app for sure!

**Comment by iamareebjamal** [comment]
Just notifying that the options callbacks aren't working right now for firestore

https://jsfiddle.net/mvwcqt43/

I kind of need the document snapshot for collections when they are loaded because pagination in firestore requires that as a param in `startAfter` and similar methods

**Comment by iamareebjamal** [comment]
Also, timestamp fields are being bound as empty objects for some reason.

**Comment by posva** [comment]
They return promises now, so no need for callbacks 😉

**Comment by iamareebjamal** [comment]
Thanks, it'd be great if you take a look at the timestamp issue

**Comment by posva** [comment]
Yes, I will. I saw it already on vuefire, non-plain objects are not converted correctly 😓 . Created #144 for that

**Comment by bmass02** [comment]
@posva Is there a reason you didn't use the functionality from the RTDB version for the Firestore version? I just created the same styled functionality for Firestore that RTDB had (bindings, creating snapshots, etc.). All objects were correctly converted (by Firebase) and just needed to be set to the store. Here is my version of Vuexfire with Firestore added: https://github.com/bmass02/vuexfire/tree/add-firestore-support. I've been using it for the past 3 months without any troubles. Also, I'd be happy to help with getting the Firestore version to production if you're looking for help.

**Comment by posva** [comment]
I simply wanted to change too many things to reuse some of the functions

**Comment by classikd** [comment]
Thanks it works well and helps me a lot. 
But I hope someone will find why that timestamp issue occurs.. :')

**Comment by xupateste** [comment]
Awesome! it works! you are a genius bro

**Comment by yoonwaiyan** [comment]
Hi, just wondering is there anything missing as I'm testing out the Firestore branch but didn't get to make it work :( This is my script:

```
<script>
import { dbExpensesRef } from './firebaseConfig';

console.log('dbExpenses', dbExpensesRef);

export default {
  created() {
    this.$store.dispatch('setExpensesRef', dbExpensesRef);
  }
};
</script>
```

in my firebaseConfig I have the ref set up:
```
const firebaseDB = firebaseApp.firestore();
// ...
const dbExpensesRef = firebaseDB.collection('expenses');

export { firebaseApp, dbExpensesRef };
```

but I saw this error in my console log instead:
<img width="614" alt="screen shot 2018-07-07 at 2 30 01 pm" src="https://user-images.githubusercontent.com/3081772/42407606-44986e7e-81f2-11e8-8253-34be3e0abbe1.png">

apparently the ref is there but it's undefined in the script. Am I missing out anything?

**Comment by posva** [comment]
Firestore has been supported for a long time now.
To track the roadmap check https://github.com/vuejs/vuefire/issues/145
