### ISSUE TITLE
Is there a way to limit queries using .limitToLast

### ISSUE THREAD

**Issue by galipmedia** [posva/vuexfire#119]
This https://jsfiddle.net/galipmedia/ko97c14o/2/ not surprisingly breaks the functionality. But is there someway to achieve this as I do not want to get millions of chat messages?

**Comment by galipmedia** [comment]
I just realised this is totally possible you just cannot cannot query top level things in firebase only children.

**Comment by posva** [comment]
It just works 😄

```js
created() {
    this.$store.dispatch('setTodosRef', todosRef.limitToLast(3))
  },
```
(https://jsfiddle.net/posva/6w3ks04x/)
