### ISSUE TITLE
Any example using with Nuxt.js

### ISSUE THREAD

**Issue by kieusonlam** [posva/vuexfire#124]
Hi guys, I dont know if I can ask question here. Can you guys show me and example using vuexfire with nuxt. I'm not quite sure what I have to do :(

**Comment by posva** [comment]
I have used vuexfire with nuxt already and works nicely. I used https://nuxtjs.org/guide/vuex-store#modules-mode

Just make sure to add `firebaseMutations`:

```js
// store/index.js
import { firebaseMutations } from 'vuexfire'

export const state = () => ({
  counter: 0,
})

export const mutations = {
  INCREMENT (state) {
    state.counter++
  },
  ...firebaseMutations,
}
```

```js
// store/quizz.js
import {
  db,
} from '~/plugins/firebase'

import { normalizeArrays } from '~/utils'
import map from 'lodash/map'
import { firebaseAction } from 'vuexfire'

export const state = () => ({
  _quizzes: [],
})

export const mutations = {
}

export const getters = {
  quizzes ({ _quizzes }) {
    return map(_quizzes, normalizeArrays)
  },
}

export const actions = {
  bindQuizzes: firebaseAction(({ bindFirebaseRef }) => {
    bindFirebaseRef('_quizzes', db.ref('quizzes'))
  }),
}
```

```js
// plugins/firebase.js
import * as firebase from 'firebase/app'
import 'firebase/database'

const config = {
  // your config
}

const provider = new firebase.auth.GithubAuthProvider()

const firebaseApp = firebase.initializeApp(config)
const db = firebaseApp.database()

export {
  db,
  provider,
  firebase,
}
```

This contains the `normalizeArrays` that you may not need but it's here just in case
```js
// utils/index.js
import reduce from 'lodash/reduce'
import map from 'lodash/map'
import omit from 'lodash/omit'

export function normalizeArrays (o) {
  return reduce(o, (prev, cur, key) => {
    if (typeof cur === 'object') {
      prev[key] = map(map(cur, toRecord), normalizeArrays)
    } else {
      prev[key] = cur
    }
    return prev
  }, {})
}

// to be called wih every object that should be in an array
// uses the key (-KtZ5JBrYwsLg0P0MUQc) to add it to the object
function toRecord (o, key) {
  return {
    '.key': key,
    ...o,
  }
}
```

**Comment by chasebank** [comment]
@posva Any known way to get this working with Firestore? All the Nuxt examples I've found are quite old. I've been trying to get something working referencing this post, and [this example](https://github.com/vuejs/vuefire/blob/master/packages/vuefire/examples/index.html) but can't crack it.

I'm assuming whatever the solution is, it would still be vuexfire instead of vuefire for now?

**Comment by posva** [comment]
For nuxt, you can wait for the action binding a reference on the nuxt fetch method. The normalization thing shouldn't be needed anymore

**Comment by chasebank** [comment]
@posva Thanks for the reply! But I still haven't been able to get this working. Actually I can't even get the plugin running. I've tried various ways of importing the plugin through the nuxt config, even with `ssr: false` or `mode: 'client'`. But I have a constant error "Cannot set property 'Vuefire' of undefined"

**Comment by posva** [comment]
I cannot know where the error comes from, that's the most common error in js 😆 
Let me share an example of how I do in my own applications. I have a `firebase` folder where I put `firestore.indexes.json`, `firestore.rules`, `index.js` (to export the db and types) and `collections.js` where I export collections refs:

```js
// firebase/index.js
import { firebase } from '@firebase/app'
import 'firebase/firestore'
import 'firebase/auth'

const config = {
  apiKey: '...',
  authDomain: '...',
  projectId: '...',
}

export const db = firebase.initializeApp(config).firestore()


// Export utility functions
export const { Timestamp } = firebase.firestore
```

```js
// firebase/collections.js
import { db } from './index'

export const users = db.collection('users')
export const matches = db.collection('matches')
```

```js
// store/index.js
import { firebaseMutations as mutations } from 'vuexfire'

export const state = () => ({})

export { mutations }
```

```js
// store/matches.js
import { firebaseAction } from 'vuexfire'
import { matches, users } from '../firebase/collections'

// omitting state, mutations, getters

const actions = {
  subscribeToAllMatches: firebaseAction(({ bindFirebaseRef }) => {
    return bindFirebaseRef('matches', matches)
  }),
  // async version
  subscribeToMatch: firebaseAction(async ({ bindFirebaseRef }, { matchRef ) => {
    await bindFirebaseRef('match', matchRef)
  }),
}
```

`pages/matches.vue`
```vue
<template>
  <div>
    <ul>
      <li v-for="match in matches">{{ match }}</li>
    </ul>
  </div>
</template>

<script>
import { mapActions, mapState } from 'vuex'

export default {
  methods: mapActions('matches', ['subscribeToAllMatches']),
  computed: mapState('matches', ['matches']),

  // return a promise
  fetched() {
    return this.subscribetoAllMatches()
  },
}
</script>
```

There is no need for a nuxt plugin, this should work in universal mode as well. You have to make sure to handle the firebase authentication (if you have any) too though

**Comment by chasebank** [comment]
Thanks so much for breaking that down! That seems to work much better.

No more errors, but I'm still having trouble binding the ref. Vuex is showing an empty object

https://github.com/chasebank/nuxt-firebase-vuexfire

Any ideas?

Thanks again!
