### ISSUE TITLE
Unknown mutation types error in modules

### ISSUE THREAD

**Issue by entioentio** [posva/vuexfire#125]
Hi Posva, at first i'd like to thank you for a wonderful lib!

I'm getting unknown mutations in modules. I'm trying to setup a store with two modules, one to manage local state and one to be in-sync with firebase DB.

```
[vuex] unknown mutation type: vuexfire/ARRAY_ADD
[vuex] unknown mutation type: VUEXFIRE_ARRAY_INITIALIZE
```

My store:
```
export default new Vuex.Store({
  modules: {
    ...appModules
  },
  strict: debug
});
```

Simplified module containing firebase DB shizzle:
```
import { firebaseMutations, firebaseAction } from 'vuexfire';

const state = {
  items: []
};

export default {
  namespaced: true,
  state,
  actions : {
    setItemsRef: firebaseAction(({ bindFirebaseRef }, ref) => {
      bindFirebaseRef('items', ref)
    })
  },
  mutations: firebaseMutations
};

```

...and this is in my *mounted()* hook:
```
this.$store.dispatch('generalVuex/setItemsRef', firebaseWrapper.db.ref('items'))
```

I've seen this issue #43 and it is not helping me. I'm quite sure that i miss some basic, obvious thing in this setup. 🤔
I'm relatively new to vue, so it may just be some typo or silly bug. Please, don't be mad at me in that case :)

**Comment by posva** [comment]
I think you're just missing the firebaseMutatations on the store. They must be *only* on the store, not in modules 🙂

**Comment by entioentio** [comment]
@posva, you're clearly a genius! It helped!

**Comment by posva** [comment]
lol, it's just because I'm the one who wrote this
