### ISSUE TITLE
Database change to trigger other store data changes?

### ISSUE THREAD

**Issue by MichaelFromin** [posva/vuexfire#140]
I have vuexfire 2 setup in my app and if I update my database it correctly updates the Vuex store.  So far so good.

The data that comes back from the store is an array so if I want to find a specific record based on its .key I have to loop through the array.

What I want to do is have a dictionary object where the keys are the Firebase `.key` so I can just say 

`dictionary[x]`  

...and get the data that has that key.  Is there some way I can trigger another mutation when vuexfire sees that my database data has changed?

**Comment by MichaelFromin** [comment]
I think I worked around this with a computed getter in the Vuex store ... Vuex appears to trigger an update of that computed getter each time the data in the state tied to Firebase is updated by vuexfire.  

Hopefully that is the correct approach.

**Comment by posva** [comment]
Yeah, that should be the correct approach but make sure you're not overcomplicating things 😄 (in term of performance) as doing only one lookup through the array whenever it is needed will be faster than building the object everytime the array changes
