### ISSUE TITLE
VuexFire.moduleMutations not working properly

### ISSUE THREAD

**Issue by DevEclipse** [posva/vuexfire#15]
so i have this code in my users module

``` js
import VuexFire from 'vuexfire'

const state = {
  auth: null,
  user: null,
  current_user: null,
  foundUser: null,
  users: null,
};

const getters = {
  getFoundUser(state) {
    return state.foundUser;
  }
};

const mutations = VuexFire.moduleMutations('users');

const actions = {
  addUser({rootState},user) {
    if(!user) return;
    rootState.refs.users.push(user);
  },
  deleteUser({rootState},user) {
    if(!user) return;
    rootState.refs.users.child(user['.key']).remove();
  },
  updateUser({rootState},user) {
    if(!user) return;
    rootState.refs.users.child(user['.key']).update(user);
  },
  getUserBy({state,rootState},{by,value}) {
    _.find(rootState.users,[by,value]);
  }
};
//called by this.$store.dispatch('addUser')
export default {
  state,
  getters,
  mutations,
  actions
}

```
and use it on my root store instance
this is just an object and will be converted to on the main js

``` js
const store = {
  state: {
    refs: null,
  },
  // modules: {
  //   stores,
  //   items,
  //   users,
  //   managers,
  //   employees,
  //   customers,
  //   transactions,
  // },
  mutations:  { ['SET_REFS'](state,payload){
    state.refs = payload;
  }},
  // mutations: Object.assign({},VuexFire.mutations,{
  //   ['SET_REFS'](state,payload) {
  //     state.refs = payload;
  //   }
  // })

};

export default store
```

then import that root store on my main js

and do store.registerModule

if i dont do that it replaces my users module states all of it
``` js
import VuexStore from './vuex';

import Vue from 'vue';
import Vuex from 'vuex';
import VueRouter from 'vue-router';
import VuexFire from 'vuexfire'
import App from './App.vue';
import VuexStore from './vuex';
import { sync } from 'vuex-router-sync';
import routes from './routes';
import firebase from 'firebase';
import db from './firebase_config';
import VueMaterial from 'vue-material'
import 'vue-material/dist/vue-material.css'

import users from './vuex/modules/users'
import items from './vuex/modules/items'
import stores from './vuex/modules/stores'
import managers from './vuex/modules/managers'
import employees from './vuex/modules/employees'
import customers from './vuex/modules/customers'
import transactions from './vuex/modules/transactions'

Vue.use(Vuex);
Vue.use(VueRouter);
Vue.use(VuexFire);
Vue.use(VueMaterial)

Vue.material.theme.register('default', {
  primary: 'blue',
  accent: 'teal'
})

const store = new Vuex.Store(VuexStore);
store.registerModule('users',users)
const router = new VueRouter({
  mode: 'history',
  routes,
});

sync(store, router);

const app = new Vue({
  router,
  store,
  firebase: {
    users: db.ref('users'),
    // items: db.ref('items'),
    // stores: db.ref('stores'),
    // managers: db.ref('managers'),
    // employees: db.ref('employees'),
    // customers: db.ref('customers'),
    // transactions: db.ref('transactions'),
  },
  render: h => h(App),
  beforeCreate() {
    if(!this.$store.state.refs) {
      this.$store.commit('SET_REFS', this.$firebaseRefs);
      // this.$store.dispatch('deleteUser', {['.key']: '-KXIgd1C7L_F5UVZ-oAM'});
    }
  }
}).$mount('#app');
```

and error pops out on the console

![image](https://cloud.githubusercontent.com/assets/19868205/20599457/3279ca24-b289-11e6-98fe-447c430e0956.png)

i dont know if my setup is right or its a bug

**Comment by DevEclipse** [comment]
and i just notice that it replaces the WHOLE state of the module by array of data from firebase 

could you please give a CLEAR example?

**Comment by posva** [comment]
You're missing to add the mutations to the root store with `VuexFire.mutations`

```js
 mutations:  {
  ['SET_REFS'](state,payload){
    state.refs = payload;
  },
  ...VuexFire.mutations
}
```

Don't register modules like that if you don't need to dynamically register modules

Also, you probably want to bind to a specific attr on the module state: `'users.user': db.ref('users/user').

About the example, you can find one on the example folder

**Comment by DevEclipse** [comment]
```
  firebase: {
    users: db.ref('users'),
    items: db.ref('items'),
    stores: db.ref('stores'),
    managers: db.ref('managers'),
    employees: db.ref('employees'),
    customers: db.ref('customers'),
    transactions: db.ref('transactions'),
  },


```

i have this on the vm root

so you mean i need to specify

users? on my module?

const state = {
  auth: null,
  user: null,
  current_user: null,
  foundUser: null,
  users: null,
};

const getters = {
  getFoundUser(state) {
    return state.foundUser;
  }
};

const mutations = VuexFire.moduleMutations('users');

but vuex only calls the mutations VUEXFIRE/arrayAdd

not users/VUEXFIRE/arrayAdd

so my users module state is replaced instead of putting the mutation state on the user module it replaces my whole users module
![image](https://cloud.githubusercontent.com/assets/19868205/20600437/a2c8e6de-b28e-11e6-878e-cc543f8c63f1.png)

i dont really get it sorry for being dumb here but can you please give a rework on my example and clear it up

**Comment by posva** [comment]
I'm sorry, but the amount of code is too damn high. There may be a bug but I'll need a minimal repro on a jsfiddle. What's wrong with the example at https://github.com/posva/vuexfire/blob/master/examples/TodoApp/modules.html ?

**Comment by posva** [comment]
I forgot, the reason yuo have mutations at `VUEXFIRE/addArray` is because it's binding to the root state: `users: db.ref('users')` instead of: `'users.user': db.ref('users/user')`.
This is valid but I don't see the need of a module if the whole state is bound to a firebase ref

**Comment by DevEclipse** [comment]
how can i separate my actions to modules and get the base state?

im using modules for separation for understanding my actions

**Comment by posva** [comment]
I'm not sure to understand the question. Maybe just create a `user` attr in the state fo the user module and bind to it:

``` js
var state = {
  users: null
}
// rest of the user module
```

``` js
// When binding
firebase: {
  'users.users': db.ref('users')
}
```

I'm sorry but I cannot help you further...
