### ISSUE TITLE
Question: how to unbind a reference when that reference no longer exists

### ISSUE THREAD

**Issue by kanethal** [posva/vuexfire#151]
I noticed that when a reference is removed from firebase directly (ie: by deleting it in the firebase console) that the bound reference in the Vuex state will persist within the observer. How might one effectively reset that state property to null when the reference no longer exists? Is there someway to set a watch on a state property to trigger an unbind when the state[property]['.value']=null ?
Thanks, great work.

```
//bind reference via Vuex Action

actions : {
   setRef : firebaseAction( ({bindFirebaseRef}, {ref}) => {
      bindFirebaseRef('family', ref)
   }
}

//console.log(vm.$store.state.family)
"{
    "data" {...}
    ".key": "-L6hS7LRP0G3-tLdm4_N"
}"

//Manually remove family reference in firebase console
//console.log(vm.$store.state.family)
"{
    ".value": null,
    ".key": "-L6hS7LRP0G3-tLdm4_N"
}"

**Comment by posva** [comment]
If I recall correctly, there was no difference between a doc being `null` and the doc not existing. This problem has been fixed for Firestore, but I'm not sure if this is feasible on RTDB

**Comment by bmass02** [comment]
Should this just unbind itself from the state, or does it need to be configurable? If it needs to be configurable, should it be configured using a callback (maybe "onDoesNotExist"?), or using a boolean (maybe "cancelOnDoesNotExist"?). This should be pretty straightforward to implement if we know how it should work. I will just depend on `snapshot.exists`.

**Comment by posva** [comment]
Closing as everything has been moved to vuefire and I'm archiving this repository
