### ISSUE TITLE
Remove optional callbacks from docs for Cloud Firestore?

### ISSUE THREAD

**Issue by bsaf** [posva/vuexfire#153]
Hi! Noticed that optional callbacks (e.g. readyCallback) do not function in 3.0.0-alpha.1 for Cloud Firestore. As @posva noted in [this comment](https://github.com/posva/vuexfire/issues/117#issuecomment-365183139), `bindFirebaseRef` returns a promise so we can check things that way.

Should we remove the optional callbacks section from the README in that case? I went in a few circles trying to get it to work today :) LMK @posva and I can do a PR.

**Comment by posva** [comment]
Yes, go ahead and fire the PR! Thanks!
I've been absent recently but I will schedule some time to rework the missing parts for vuefire/vuexfire for Cloudstore. Some minimal docs would be nice and that PR would help 👍
