### ISSUE TITLE
Working with single file components

### ISSUE THREAD

**Issue by chasebank** [posva/vuexfire#156]
This seems like it will work perfectly, but is there an example with single files?

I'm working off the todo example [JS fiddle](https://jsfiddle.net/6w3ks04x/106/),

But in the component...
```
created() {
    this.$store.dispatch('setTodosRef', todosRef)
  }
```
The ref obviously comes up undefined when it's in a different file. Is there something I'm suppose to be importing to get access to that?

**Comment by posva** [comment]
I personally import the `db` (that I export in another file) in my components so I can build up the references

**Comment by chasebank** [comment]
Thanks for the reply, that does indeed work for pushing new items. However I'm a little confused as to what the `setTodosRef` action is doing in this case? And I don't think the getter is working. I can see the new items push to the Firebase console, but I'm not seeing anything in the vuex store.

I have a new file to export the db `store/firebaseSetup.js`
```
import * as firebase from 'firebase'

var config = {
  ...
};

var firebaseApp = firebase.initializeApp(config)
var db = firebaseApp.database()

export default db;
```
Then in `store/index.js`
```
import db from './firebaseSetup.js'

var todosRef = db.ref('todos')

... all the other Vuex stuff just like the JS Fiddle
```
And then in a component
```
import { mapGetters } from 'vuex'
import db from '../store/firebaseSetup.js'

export default {
  data() {
    return {
      newTodoText: ''
    }
  },

  computed: {
    ...mapGetters(['todos'])
  },

  methods: {
    addTodo: function() {
      if (this.newTodoText.trim()) {
        db.ref('todos').push({
          text: this.newTodoText,
        })
        this.newTodoText = ''
      }
    }
  },

  created() {
    this.$store.dispatch('setTodosRef', db.ref('todos'))
  }
})
```

The new item posts to the firebase console with or without the `setTodosRef` action (?) but either way I'm getting an empty array in Vuex.

Thanks again for your help!

**Comment by posva** [comment]
Well, you have to make sure you're binding the right ref, I don't see where the problem is coming 😅

**Comment by chasebank** [comment]
I found [this repo](https://github.com/LennonSantos/vuexfire-single-file-components) which uses vuexfire in single-file components, and works.

I spent most of the day starting up new projects and comparing them to that repo, trying to figure out why they weren't working, and have finally narrowed it down to the pwa template!?

If I create a new app using `vue create ...` and choose the features manually, vuexfire works perfectly, **as long as I don't include the progressive enhancement features.** If I include pwa, vuex doesn't read from firebase. Very strange.

**Comment by bsaf** [comment]
What does the rest of your store.js look like?

**Comment by chasebank** [comment]
Nothing, it's mostly a replica of all the examples I've found

```
import Vue from 'vue'
import Vuex from 'vuex'
import VuexFire from 'vuexfire'
import { firebaseMutations, firebaseAction } from 'vuexfire'

Vue.use(Vuex)

export default new Vuex.Store({
  // VuexFire will check the type of the property to bind as an array or as
  // an object
  strict: true,
  state: {
    todos: []
  },
  mutations: firebaseMutations,
  getters: {
    todos: state => state.todos,
  },
  actions: {
    setTodosRef: firebaseAction(({
      bindFirebaseRef
    }, ref) => {
      bindFirebaseRef('todos', ref)
    }),
  },
})
```
Then a separate firebase config
```
import firebase from 'firebase'

export const  db = firebase.initializeApp({
  api stuff...
}).database()
```
Then in the component
```
import { mapGetters } from 'vuex'
import {db} from './../firebase_config.js';

var todosRef = db.ref('todos')

export default {
  name: 'HelloWorld',
  props: {
    msg: String
  },
  computed: mapGetters(['todos']),
  created() {
    this.$store.dispatch('setTodosRef', todosRef)
  }
}
```

In the pwa template, todos comes up empty. Without the pwa, vuex connects to firebase successfully.

**Comment by bsaf** [comment]
Hi @chasebank – I just set up a fresh project using Vue CLI with PWA enabled and everything worked as expected. [Here's the code](https://github.com/bsaf/vuexfire-pwa) if you want to take a look, and here's a [live version](http://vuex-pwa.surge.sh/) 👍

**Comment by chasebank** [comment]
Thanks for your help, I appreciate it!

But you're initializing Firebase inside the component. So it seems to me no surprise that it's working. But this is quite different from the [non-pwa repo](https://github.com/LennonSantos/vuexfire-single-file-components) I linked to in my previous post, as well as @posva suggestion of importing the `db` refs from a different file.

Having to re-initializing firebase _and_ re-set up the db refs in every component seems a little repetitive to me. I suppose it could be done in a mixin but still seems verbose. But I'm still new and don't understand half of what I do... :)

Can you get the pwa working more similarly to https://github.com/LennonSantos/vuexfire-single-file-components ?

**Comment by bsaf** [comment]
Hi @chasebank – just move the Firebase initialisation to `main.js` and do the `export const db = fbApp.database()` from there 😊Then just import `db` wherever you need it. Did you try it?

**Comment by chasebank** [comment]
### Yes!

As far as I can tell, that's working beautifully 😊

Thanks again

**Comment by chasebank** [comment]
@bsaf @posva I think I've found the source of my insane frustration. I thought I had this working last night but have again spent the last few hours trying to get it to work.

The connection to Firebase is only working if I set the `todosRef` variable in the component with the dev server already running, and let it hot-reload. If I refresh the browser manually, it breaks the connection **AND** when I restart the server, the connection is broken.

What I mean by "broken" is the console error: `Uncaught TypeError: Cannot read property 'ref' of undefined`.

The only way I've found to fix this, is to comment out the `todosRef` variable
```javascript
import firebase from "firebase"
import { mapGetters } from "vuex"

import {db} from './../main.js'

// var todosRef = db.ref("todos")

export default {
  name: "TodosList",
  computed: {
    ...mapGetters(["todos"])
  },
  created() {
    this.$store.dispatch("setTodosRef", todosRef)
  }
}
```
Wait for the server to auto-refresh, and then un-comment it
```javascript
import firebase from "firebase"
import { mapGetters } from "vuex"

import {db} from './../main.js'

var todosRef = db.ref("todos")

export default {
  name: "TodosList",
  computed: {
    ...mapGetters(["todos"])
  },
  created() {
    this.$store.dispatch("setTodosRef", todosRef)
  }
}
```
Then the connection with Firebase is re-established and everything works... Until I accidentally manually refresh, or close the server. When I start the server back up, I once again have to comment/un-comment the `todosRef` var.

For what it's worth I'm on Chrome 65.0.3325.181 and Windows 10

**Comment by posva** [comment]
Cannot test at the moment but I remember not having trouble with HMR. I had my db export in a different file from `main.js` and was directly creating the ref whenever I needed (in the created hook `db.ref('todos')` instead of `todosRef`)

**Comment by bsaf** [comment]
I am away right now but I do remember noticing that `db` is `undefined` until the component is mounted (I think...) – so can you try putting the `db.ref` directly in the query and see if that works?

**Comment by chasebank** [comment]
Thanks again to you both! I think that nailed it. I was still having issues calling the `setTodosRef` action multiple times (in parent and child) but then it occurred to me that I just need to run that action once at the root level, and then the getters will handle the rest.

And then for the mutations in the components, I'm using the same longform `db.ref('todos')` and everything is working fine!

So what I'm left with is

**firebase_config**
```javascript
import firebase from 'firebase'

export const db = firebase.initializeApp({
  databaseURL: 'https://vuefiredemo.firebaseio.com'
}).database()
```
**store**
```javascript
import Vue from 'vue'
import Vuex from 'vuex'
import VuexFire from 'vuexfire'
import { firebaseMutations, firebaseAction } from 'vuexfire'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    todos: []
  },
  getters: {
    todos: state => state.todos,
  },
  mutations: {
    ...firebaseMutations
  },
  actions: {
    setTodosRef: firebaseAction(({
      bindFirebaseRef
    }, ref) => {
      bindFirebaseRef('todos', ref)
    })
  }
})
```
**App.vue**
```javascript
import { db } from './firebase_config'

export default {
  name: 'app',
  created() {
    this.$store.dispatch("setTodosRef", db.ref('todos'))
  }
}
```
**route/component**
```javascript
import { mapGetters } from "vuex"
import { db } from './../firebase_config'

export default {
  name: "todos",
  data() {
    return {
      newTodoText: ''
    }
  },
  computed: {
    ...mapGetters(["todos"])
  },
  methods: {
    removeTodo: function(todo) {
      db.ref('todos').child(todo['.key']).remove()
    },
    addTodo: function() {
      if (this.newTodoText.trim()) {
        db.ref('todos').push({
          text: this.newTodoText,
        })
        this.newTodoText = ''
      }
    },
    updateTodoText: function (todo, newText) {
      db.ref('todos').child(todo['.key']).child('text').set(newText)
    }
  }
}
```
Let me know if anything stands out as wrong/could be improved
