### ISSUE TITLE
null value in firestore document gives an error

### ISSUE THREAD

**Issue by R4YM3** [posva/vuexfire#158]
Hi there,

First thanks for all the great work on Vue!

Currently i'm getting the error `Uncaught TypeError: Cannot read property 'longitude' of null`, when i'm trying to get a document within a collection. The occurs in vuexfire.es.js in the function extraRefs() in the reduce'r.

My store:
```
const user = {
    namespaced: true,
    state: {
        data: {}
    },
    actions: {
        login: firebaseAction(({
            bindFirebaseRef
        }, user) => {
            bindFirebaseRef('data', db.collection('users').doc(user.uid))
        })
    }
}

new Vuex.Store({
    strict: true,
    modules: {
        user
    },
    mutations: {
        ...firebaseMutations
    }
})
```

the document exist of:
```
{
    disabled: false
    email: "foo@bar.com"
    email_verified: false
    foo: null
}
```

After some debugging i noticed that `null` values within a document generates this error. When I delete the key `foo` with value `null`, then there's no error and is see the data in the vuex store.

currently fixed it locally by adding the following in the extraRefs() reduce'r 

```
if (ref === null) {
    tot[0][key] = ref
    return tot
}
```

**Comment by posva** [comment]
Thanks for reportingn back!
