### ISSUE TITLE
bindFirebaseRef as a promise

### ISSUE THREAD

**Issue by R4YM3** [posva/vuexfire#159]
I would like bindFirebaseRef and unbindFirebaseRef to be a promise.

Currently i got the situation I need to logout a user, to achieve this i'm doing the following.
1. unbindFirebaseRef
2. logout on firebase

The code would look something like this:
```
logout: firebaseAction((context, user) => {
    context.unbindFirebaseRef('users')
    firebase.auth().signOut().then(() => {
        // doing some other stuff
    })
})
```

When I run the code firebase.auth().signOut() is finished before context.unbindFirebaseRef('users') 
giving this error: `Error in created hook: "TypeError: sub[key] is not a function"`
Error is generated here:
```
function unbind (ref) {
  var commit = ref.commit;
  var key = ref.key;

  var sub = subscriptions.get(commit);
  if (!sub) { return }
  // TODO dev check before
  sub[key]();
  delete sub[key];
}
```
--------------------

I would also like to do the following:
```
login: firebaseAction((context, user) => {
    context.bindFirebaseRef('data', db.collection('users').doc(user.uid)).then(() => {
        context.commit('SET_READY', true)
   )
}),
```

**Comment by classikd** [comment]
I am pretty sure those methods return promises, did you try like that maybe
`
context.unbindFirebaseRef('users').then(() => {		
	firebase.auth().signOut().then(() => {
		// doing some other stuff
	})
})
`

**Comment by posva** [comment]
It is true for v3 of vuexfire but not for v2. unbinding doesn't return a promise though, there's no need

**Comment by R4YM3** [comment]
Hi classikd, i've tried that piece of code but does not work.

I've updated a example jsfiddle with a unbind, within this you can see that the promise does not work. see: https://jsfiddle.net/mvwcqt43/16/

**Comment by R4YM3** [comment]
How do you mean no need? 

How do I else know that the unbind is done?  I can imagine that is handy for in example removing the data after the unbind.

**Comment by classikd** [comment]
Trying to help before posva or someone better than me helps you^^
Here is my current way of doing : 
```
methods: {
  disconnect () {
    this.$store.dispatch('user/logout')
      .then(() => this.$store.dispatch('todo/setTodos', null))
      .then(() => { this.$router.push({ name: 'home-index' }) })
  }
}
```
[https://jsfiddle.net/c2r2ofpp/](https://jsfiddle.net/c2r2ofpp/)

**Comment by posva** [comment]
This has been implemented and will be released in next version (which is tracked under vuejs/vuefire)
