### ISSUE TITLE
Dynamic binding

### ISSUE THREAD

**Issue by gustavopch** [posva/vuexfire#16]
Suppose I have an index of users in a group:
```
group: {
  user1: true,
  user7: true,
  user15: true,
  etc...
}
```

I want to bind references to each of these users to the store:
```
for (const userKey in group) {
  this.$bindAsObject('users.${userKey}', db.ref('users/${userKey}'))
}
```

It seems that it's not possible. Is there anything I can do instead?

**Comment by posva** [comment]
yes, it works use backticks if you're looking for string interpolation:

``` js
`users.${userKey}`
```

If it still doesn't work, please, provide a jsfiddle

**Comment by gustavopch** [comment]
Sorry, the single quotes were a typo. I know about the backticks.

Let me quickly try to explain again before a jsfiddle:
Binding to `users` works; binding to a child property `users.user7` for example doesn't. I guess Vuexfire can only bind to properties that were explicitly predefined in the `state` object.

**Comment by posva** [comment]
Oh, yeah that doesn't work. Properties have to be at the root of the state.
The dot delimiter only lets you access vuex modules but no state
subproperties

**Comment by gustavopch** [comment]
Wouldn't it be good to allow the use of the dot delimiter to bind to specific children in situations like the case that I described in the first post? Or is there another solution?

**Comment by posva** [comment]
The dot is used for modules. Maybe using slashes but I don't want to make the syntax too complicated either.
Maybe you can create a query that retrieves your group of users and keep that in an array or object

**Comment by gustavopch** [comment]
It doesn't seem to be possible to query Firebase for multiple keys. Could you explain me how to approach this case? I've read Firebase docs, StackOverflow's questions, etc. multiple times and couldn't find any similar case even though it seems such a common situation.

**Comment by posva** [comment]
Well, that's a bit complicated indeed. You may laugh but here's a solution: https://youtu.be/sKFLI5FOOHs?t=9m29s
