### ISSUE TITLE
"ref" is "undefined" after passing it to enhanced action using Firestore

### ISSUE THREAD

**Issue by sagaio** [posva/vuexfire#163]
I've followed the examples given but I'm unable to get the `firebaseAction `to work properly since the `ref` is `undefined` for some reason I can't understand
In one of my store modules I have this action:

```
  actions: {
    getLogTypes: firebaseAction(({ bindFirebaseRef }, { ref }) => {
      console.log(ref) // <-- prints out "undefined"
      bindFirebaseRef('logTypes', ref)
    })
  }
```
I of course have the `logTypes` in my local state.

I call my action from a component in the `mounted ()` phase like this (I have hardcoded the ID just to make sure):
(`this.db` is a getter which points to `firebase.firestore()`)
```
  mounted () {
    console.log(this.db.collection('companies').doc('2342341vxfv1')) // <-- prints out DocumentReference with given ID 2342341vxfv1 = working
    const logTypesRef = this.db.collection('companies').doc('2342341vxfv1')
    this.$store.dispatch('logs/getLogTypes', logTypesRef )
  }
```

and I get the folllowing error, which is expected since the `console.log(ref)` in my `firebaseAction `prints out `undefined`.

```
Uncaught (in promise) TypeError: Cannot read property 'where' of undefined
    at eval (vuexfire.es.js?b50a:430)
    at new Promise (<anonymous>)
    at bind (vuexfire.es.js?b50a:429)
    at context.bindFirebaseRef (vuexfire.es.js?b50a:469)
    at eval (index.js?7627:41)
    at Store.firebaseEnhancedActionFn (vuexfire.es.js?b50a:472)
    at Array.wrappedActionHandler (vuex.esm.js?358c:704)
```

Why is the `ref` undefined in my enhanced action?

**Comment by posva** [comment]
The error is because of js destructuring (I recommend you give that a search 🙂 )

You either need to `this.$store.dispatch('logs/getLogTypes', { red: logTypesRef })` or change the signaruter of the action to `getLogTypes: firebaseAction(({ bindFirebaseRef }, ref) `
