### ISSUE TITLE
Question about modules and the docs

### ISSUE THREAD

**Issue by mesqueeb** [posva/vuexfire#174]
I'm new to your library and IT LOOKS GREAT!
I want to use it, but...... I'm having a very hard time understanding what exactly is happening, what the library creates in the store etc.

You wrote:

> It works with modules as well, but you don't need to add the mutations there:
```js
const store = new Vuex.Store({
  modules: {
    todos: {
      state: {
        todos: [], // Will be bound as an array
        user: null // Will be bound as an object
      },
    }
  }
})
```

I'm very confused why you create a module called `todos` and then it has a state with again `todos` and also `user`...

**Comment by posva** [comment]
Thanks, I'm glad you like it!

It's just an example, so it doesn't matter much about what's inside 😄 
I updated the readme to a different example though
