### ISSUE TITLE
SSR bindFirebaseRef

### ISSUE THREAD

**Issue by baronTommy** [posva/vuexfire#188]
Nuxt.js + vuexfire
Does it work with SSR?

`pages/users.vue`
```js
// bind NG
async fetch({store}) {
   await store.dispatch('users/bindFirebase')
},

// bind NG
async asyncData({store}) {
    
   await store.dispatch('users/bindFirebase')
},

// bind OK
async created () {
    await this.$store.dispatch('users/bindFirebase')
}
```

`store/users.js`
```js
bindFirebase: firebaseAction(async ({bindFirebaseRef}) => {
    await bindFirebaseRef('list', usersRef)
})
```

**Comment by posva** [comment]
yes, it works if you wait for bindFirebaseRef in asyncData

**Comment by baronTommy** [comment]
@posva Thank you

**Comment by dac3971** [comment]
@posva is there a simple example of bindFirebaseRef with Nuxt for Firestore? I'm simply trying to bind to a single document.  I have my `dispatch` in `asyncData` as below,.  It fetches the data initially but doesn't update live.

`  async asyncData ({params,store}){
    if(store.getters.user.uid)
      await store.dispatch('g/checkFollowing', `groups/${params.id}/follows/${store.getters.user.uid}`)
    return {}
  },`
