### ISSUE TITLE
What is the status on v3 (firestore branch)?

### ISSUE THREAD

**Issue by shongololo** [posva/vuexfire#191]
It appears that the most recent commits are on v2 and that v3 (firestore branch) is still in beta.

Wondering if the long term plan is to continue development / support for firestore branch and what the general intent is going forward regarding firestore vs. realtime database etc?

Thanks!

**Comment by posva** [comment]
hello, the v3 is the most active one. It has been on alpha for a long time but it is stable. I'm refactoring the code to make to make it possible to use both firestore and RTDB in the same application which is currently not possible.
The refactoring is happening on https://github.com/vuejs/vuefire/tree/lerna
there will still be 2 packages: vuefire and vuexfire

**Comment by shongololo** [comment]
Thanks for the update.

Does it possibly make sense to separate the Firestore and RTDB versions into separate modules? I'm assuming people will increasingly drop RTDB over time...

**Comment by posva** [comment]
It will be tree-shakable 😉
