### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by FlorianChretien** [posva/vuexfire#205]
Hello,

Sorry to bother you but I am stuck for many days without moving forward ... Can not make the example work ...

Do you have a track? See the solution? I searched everything but I can not find ... Really sorry for this idiot question :/

thanks

store
<img width="498" alt="screenshot at nov 25 21-05-58" src="https://user-images.githubusercontent.com/3511773/48983984-3ebd1400-f0f6-11e8-8acb-1286d701c302.png">

component
<img width="497" alt="screenshot at nov 25 21-05-48" src="https://user-images.githubusercontent.com/3511773/48983987-41b80480-f0f6-11e8-84bd-4636f8cada54.png">

(VueCli with VueRouter, Vuex, Webpack ...)

**Comment by posva** [comment]
if you put the data from the store in data, it will take the initial value (empty array). Use a computed property instead:

```js
computed: {
  todos () {
    return this.$store.todos
  }
}
```
(you should check vuex docs 😛 )

**Comment by FlorianChretien** [comment]
I tried otherwise and it still does not work ....: '(
Thank you for your help!

(Yet it works with viewfire)

store
<img width="494" alt="screenshot at nov 26 16-39-51" src="https://user-images.githubusercontent.com/3511773/49024666-4f26ca80-f19a-11e8-9d79-59b67555c846.png">

component
<img width="431" alt="screenshot at nov 26 16-39-41" src="https://user-images.githubusercontent.com/3511773/49024677-564dd880-f19a-11e8-9b9e-cecfeba5f7dd.png">

**Comment by aspben** [comment]
Something tell me that it's à problem with the firebase ref syntax. Did you try firebase. Database().Ref('utilisateurs')

**Comment by FlorianChretien** [comment]
Hi! 
Thank you for your response @aspben. I use the following list :
<img width="231" alt="screenshot at nov 26 17-09-09" src="https://user-images.githubusercontent.com/3511773/49026432-29032980-f19e-11e8-83f8-f8399ae6f95b.png">

If I try to replace .ref with .collection I will make an error .. :/
"_services_firebase_firebase__WEBPACK_IMPORTED_MODULE_6__.db.collection is not a function"

It's a base for me that works if I use vuefire. My config :  
<img width="291" alt="screenshot at nov 26 17-12-29" src="https://user-images.githubusercontent.com/3511773/49026577-7ed7d180-f19e-11e8-88e9-b9494d948df5.png">

**Comment by aspben** [comment]
I just checked. On my project the version is alpha-9 and I use firestore. Im not sure vuexfire work for both database. Maybe check into that.

**Comment by posva** [comment]
vuefire < 2 is for the RTDB, vuexfire > 3 and vuefire > 2 are for Firestore. In the future, newer versions will support both versions but right now it doesn't

**Comment by FlorianChretien** [comment]
Yes my bad ! 😄 Thanks toi vert much @aspben @posva
