### ISSUE TITLE
Support of Firestore

### ISSUE THREAD

**Issue by SumNeuron** [posva/vuexfire#208]
Following [James2Doyle](https://github.com/james2doyle/nuxt-firebase-auth)'s example,
if you change the accounts`database` to a `firestore` in the file `/store/index.js`

```js
const actions = {
  setAccountRef: firebaseAction(({ bindFirebaseRef }, path) => {
    return bindFirebaseRef('account', firebase.firestore().doc(path)) // firestore
    // return bindFirebaseRef('account', firebase.database().ref(path)) // <--- original
  }),
...
}
```

doesnt work, throwing: TypeError: "source.on is not a function"

using `ref` throws

"firebase__WEBPACK_IMPORTED_MODULE_3___default.a.firestore(...).ref is not a function"

please add support for firestore

**Comment by posva** [comment]
Answered in vuefire
