### ISSUE TITLE
Documentation Request: paginated ref

### ISSUE THREAD

**Issue by SumNeuron** [posva/vuexfire#209]
In your example of a todo app, binding the entire todo list is not a problem as if it were a product app, a user would likely never have hundreds if not thousands of todos. 

So, it would be relevant to have a paginated example with an associated getter for the page.

**Comment by posva** [comment]
added to https://github.com/vuejs/vuefire/issues/145

**Comment by posva** [comment]
btw, you can use computed properties or watcher to automatically rebind
