### ISSUE TITLE
Infinite Recursion?

### ISSUE THREAD

**Issue by SumNeuron** [posva/vuexfire#211]
So I am using `vuexfire` (3.16) based on an example (see https://www.davidroyer.me/blog/nuxtjs-firebase-auth/) 

and for whatever reason using the `setUser` mutation with the action 

```js
setProfileRef: firestoreAction(({ bindFirestoreRef }, uid) => {
    return bindFirestoreRef('profile', firebase.firestore().collection('profiles').doc(uid))
  }),
```

results in infinite recusion

**Comment by posva** [comment]
Hey, I really cannot help with this. Make sure to use the latest version of vuexfire (next tag)
Even with circular refs, there is max depth limit. I don't know about the blog but I don't endorse any content beyond https://vuefire.vuejs.org.

Oh and we moved this to vuefire
