### ISSUE TITLE
Support for storage?

### ISSUE THREAD

**Issue by SumNeuron** [posva/vuexfire#212]
I didn't see any issues referring to storage.
Are there plans for / will there be support for firebase storage?

suppose one has a "blog" app.

in `firestore` they have the following collections

```
profiles # <--- extra user info linked to firebase.auth
posts # <--- links profiles, storage ref and  tags
tags
```

and in storage they have 
```
blog/
    posts/
        post1key.md
        post2key.md
```

currently  `firebase.storage().ref().child('blog/posts/post1key.md')` does not work as a valid ref.

Would be nice if this could be added (and also handle blob conversion)

**Comment by posva** [comment]
there aren't plans for the moment as the firebase js sdk seems to be enough
