### ISSUE TITLE
npm run build fails: rollit not found

### ISSUE THREAD

**Issue by vonwao** [posva/vuexfire#213]
See full output below.  Also, why do you need to run build for example?  This is not clear. 

> vuexfire@3.0.0-alpha.5 build C:\Users\Otto\Documents\iblink\vuexfire
> rollit

'rollit' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuexfire@3.0.0-alpha.5 build: `rollit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuexfire@3.0.0-alpha.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by posva** [comment]
We moved to vuefire repo
