### ISSUE TITLE
Struggling to Identify Best Practice

### ISSUE THREAD

**Issue by arranf** [posva/vuexfire#24]
I'm struggling to identify ways to keep vuefire and vuexfire DRY. 

It appears in order to perform operations like add, remove, update I need access to a database reference for the objects. It doesn't appear I can use vuexfire like vuex in the sense that I can dispatch actions and commit mutations to alter them. Am I right in thinking the best way to keep things clean is to create a module that contains an instance of each type of ref I need and export them to make them available.

Additionally, I can't seem to find a way to access user specific database references?

I tried to create a callback that would change my references after auth but these all fail with the error
`vue.common.js?e881:435 Error: VuexFire: invalid Firebase binding source.`

**Comment by posva** [comment]
The API for v1 of vuexfire isn't aligned with vuex, that's why it completely changes for the v2.
This v2 can be tested on the branch v2. There's something I need to implement in Vuex to make the usage easier. Once this is merged I'll release the v2 under the `next` tag so people can enjoy a much better API

> It appears in order to perform operations like add, remove, update I need access to a database reference for the objects. It doesn't appear I can use vuexfire like vuex in the sense that I can dispatch actions and commit mutations to alter them.

In the v2 you still need to use the references to updates the database, but you can do so in the actions.

> Additionally, I can't seem to find a way to access user specific database references?

I'm not sure to understand this. Nothing should change when using vuefire or vuexfire about this.

> I tried to create a callback that would change my references after auth but these all fail with the error
vue.common.js?e881:435 Error: VuexFire: invalid Firebase binding source.

You're simply passing something that is not a reference. A valid one looks like `db.child('users')`

**Comment by arranf** [comment]
@posva Thanks responding. The reason this is an issue with vuexfire is because you can declare firebase as a function of a component with vuefire

```
firebase () : {
    return db.ref('users').child(this.getUID)
}
```

This however throws errors with vuexfire. I found [this](https://forum.vuejs.org/t/vue-routes-firebase-auth-sync-problem/4470) pattern of using a getRef() method, is this good or bad practice? It allows me to separate my actions out (which is necessary for my application) but I feel like there could be a significant performance hit.

Note: I'm more than happy to produce a sample application to demonstrate the practices discussed to help others.

**Comment by posva** [comment]
If you're using vuexfire and vuefire at the same time, note it isn't supported and won't work.
Can you extract the relevant part of the topic you sent me so I can tell you what I think?
If it's about auth, you probably need to unbind and find on authentication change. With vuexfire 2, you can do something like: https://github.com/posva/vuexfire/issues/14#issuecomment-272724098

**Comment by arranf** [comment]
@posva I'm not using vuefire and vuexfire together. The comparison was just to point out with vuefire you can delay the binding which means you can use a computed property for the ref.

This is related part.
```
// database.js
import firebase from 'firebase'

let database = null

const init = function () {
  database = firebase.database()
}

const getRef = function (path) {
  return database.ref(path)
}

const getDb = function () {
  return database
}

export default { init, getRef, getDb }

// MyComponent
export default {
  data: () => {
    return {
      items: []
    }
  },
  created: {
     items: this.$bindAsArray('items', database.getRef(`items/${user.uid}`))
   },
}
```

**Comment by posva** [comment]
Ooh, right. I introduced that some days ago into vuefire but didn't add it to vuexfire. I'll add it. Thanks for pointing it out!

**Comment by arranf** [comment]
@posva Glad to see I'm not going crazy! 
Any comments on the getRef method?

**Comment by posva** [comment]
It's fine. You can also export the whole db but using functions and exposing a shorter API is a good idea 👍

**Comment by arranf** [comment]
Okay great. Thanks for you help @posva !

**Comment by toyflish** [comment]
if I understand right my mutations on the vuex-store don't affect the firebase-store, if I want to mutate up to firebase I have to do it through the firebase-refs in Vue.
I ended up sending a commit including the firebase-ref in the payload. Is it possible to bind only the Vuex-store to firebase instead of having the bindings in Vue?

**Comment by posva** [comment]
@toyflish yes

>  Is it possible to bind only the Vuex-store to firebase instead of having the bindings in Vue?

I'm not sure to understand that.
You may want to look the v2 branch but you'll be on your own: the examples are updated but the readme is not. The api will probably change in the future.

**Comment by toyflish** [comment]
thanks I have taken a look at the todo example. In index.html you  operate directly on the firebase-ref in the addTodo/removeTodo methods.
I would like to add a mutation in the store and commit that mutation in addTodo/removeTodo or anywhere in my app and the store that is bound to firebase cares about updating firebase. I thought that is what you want from using Vuex, commiting everything in mutations from everywhere in the app.
I added the addItem-mutation to the example https://github.com/posva/vuexfire/blob/v2/examples/TodoApp/index.html
```
    var store = new Vuex.Store({
      // VuexFire will check the type of the property to bind as an array or as
      // an object
      state: { items: [] },
      mutations: Object.assign({}, VuexFire.mutations,{
        addItem: function (state,text) {
          state.items.push({text: text})
        }
      }),

      getters: {
        items: state => state.items
      },
      actions: {
        setItemsRef (context, ref) {
          bind('items', ref)
        }
      },
      plugins: [VuexFire.default]
    })
```
and then commited it 

```
vm.$store.commit("addItem", "grab them by the pussy")
```

now it's in my local store but it's not persisted to firebase.

**Comment by posva** [comment]
You need to use an itemRef: https://github.com/posva/vuexfire/blob/v2/examples/TodoApp/index.html#L70

**Comment by toyflish** [comment]
but then in sub-components I have to refer to global itemRef or have to call a method on $root, that's not really a beauty

**Comment by posva** [comment]
you have multiple patterns to make it _beatiful_. You simply need to keep the ref somewhere accessible for all subcomponents or pass it as a prop. Ideally, your components should be dispatching actions instead of directly relying on the ref

**Comment by arranf** [comment]
Eduardo, I think this is where the examples are lacking!

**Comment by posva** [comment]
I can definitely go deeper about it in a blog post in the future. Maybe there's something doable to make it easier in Vuexfire, like keeping all references in a object so actions can refer easily get the reference hold by a key

**Comment by quangv** [comment]
Related to #70
