### ISSUE TITLE
Sources being unset and set to null when bound via function

### ISSUE THREAD

**Issue by jatatech** [posva/vuexfire#29]
Hi,

I have several single file components which use the same state variables.  These components are linked between each other using vue-router.

Firebase is instantiated via function:
```javascript
firebase: function() {
      var self = this;
      var startTime = 12345678;
      var tmpUid = 12345;
        return {
          overtimeBlocks: {
            source: db.ref('/overtime/' + tmpUid + '/blocks/').orderByChild("clockin").startAt(startTime),
            asObject: false
          },
          overtime: {
            source: db.ref('/overtime/' + tmpUid + "/").orderByChild("name"),
            asObject: false
          }
      }
}
```

And similarly (but with different parameters) in another component.

When routed between components, the state variable correctly loads each array element (shown within Vue-DevTools, but then is sent a "VUEXFIRE/objectValue" with a payload of `{Key: "overtime", Record: null}` which obviously sets the state variable to null and removes the loaded firebase data array.

Has anyone else experienced similar?

Many thanks,
Jake.

**Comment by posva** [comment]
Can you provide a **minimal** repro, please? There's a jsfiddle in the example/TodoApp/index.html file you can use as a base

**Comment by jatatech** [comment]
Hiya,

Happy to, however as it's an issue that seems to be caused by using single file components (and also driven by route changes using vue-router), it might not be such a minimal repro.

Any suggestions as to how best to reduce the clutter for you?

Many thanks,
Jake.

**Comment by posva** [comment]
hey, well try to reproduce it without routing nor sfc first. If that's not possible, create a repo and include vue-router but make sure to boil down the best you can so I can help you

**Comment by jatatech** [comment]
Hi Posva,

Whilst I'm working on a boiled down repro.  I've tracked the issue down to a race issue.

When the route is changed, the newly created component instantiates the firebase element successfully into the store, then (shortly after this) when the previous component is destroyed it unbinds the object.

This obviously only occurs when sharing store variables between components.

Many thanks,
Jake.

**Comment by posva** [comment]
I see. Glad you found the issue!
