### ISSUE TITLE
Vuex Issue

### ISSUE THREAD

**Issue by niallobrien** [posva/vuexfire#3]
I tried adding this after scaffolding a project with Vue-cli (using webpack#2.0), but I get the following error in the browser console after following the docs.

`Uncaught TypeError: _vuexfire2.default.mapGetters is not a function`

Please advise, thanks.

**Comment by posva** [comment]
You'll have to provide a minor repro on jsfiddle for me to help you. You need Vuex 1 or Vuex 2 for vuexfire to work

**Comment by niallobrien** [comment]
It's safe to close this issue for now.
