### ISSUE TITLE
Data added twice localy after vue router navigation where the same data references exists

### ISSUE THREAD

**Issue by Tim86** [posva/vuexfire#33]
As I explained [here](https://github.com/posva/vuexfire/issues/28) i got an issue where data is added twice to the local array and once (as supposed to the remote firebase database). The issue can be reproduced with my [issue demonstrator repo](https://github.com/Tim86/vuerouter-vuexfire-issuedemo) which is a trimmed down repo. I suspect the issue lies in the data binding but I'm unsure how to do it correctly.

**Comment by posva** [comment]
what is wticy?

**Comment by posva** [comment]
Closing, inactivity

**Comment by nhaga** [comment]
Not sure if that was the problem, but I can share the issue i was having and how I solved it.
If you repeat "mutations: VuexFire.firebaseMutations," on each module, the state data will be repeated as many times as the number of modules.

I moved the mutations to the store index and all was good.
