### ISSUE TITLE
Vue-cli

### ISSUE THREAD

**Issue by niallobrien** [posva/vuexfire#4]
Hi, just a thought - with 2.0 around the corner, I thought it would be very cool to have a Webpack template for Vue 2.0 with Vuex/Vuexfire & Firebase setup and pre-configured (possibly with Bootstrap 4 included) as I can certainly see myself using this stack a lot more and would like to be able to get up and going very quickly for each new app.

Is this something you'd be interested in, or am I best to just fork the Webpack template and create something for my own needs? Obviously this isn't the correct repo (Webpack template for Vue-cli), but wanted to run it by you first.

Thanks in advance.

**Comment by posva** [comment]
Hi! Yes, you're better on yourself since this has nothing to deal with vuexfire. IMO vuexfire is simple enough to add to a project. There's an example that also shows firebase code. Good luck!
