### ISSUE TITLE
Unable to get working correctly

### ISSUE THREAD

**Issue by niallobrien** [posva/vuexfire#6]
Hi @posva - best to open an issue here. Myself and @microcipcip are having issues getting Vuexfire working correctly in a typical Webpack setup.
I have provided an example repo [here](https://github.com/niallobrien/Vue-Vuex-Firebase). This should connect straight to my Firebase database, you can see the Vuex store populate with the data from Firebase, however, it is not updating the DOM.

Would you mind taking a look please, so that we can provide a solid example for others looking to use Vuexfire with a project generated with Vue-CLI?

Thanks in advance.

**Comment by posva** [comment]
I tried out your project and make it work. You're using modules but vuexfire does not support modules yet.
I modified the code to make it work: https://github.com/posva/Vue-Vuex-Firebase
Unfortunately, I cannot dig further into your example

**Comment by posva** [comment]
What do you mean? I'm using webpack there

**Comment by niallobrien** [comment]
Sorry, I meant modules.

**Comment by posva** [comment]
Aah. Of course. That's something planned. Let me open an issue so I don't forget 😄
