### ISSUE TITLE
Question: Iterating children of a mapped firebase reference

### ISSUE THREAD

**Issue by dsl101** [posva/vuexfire#62]
I'm wrestling a bit with how best to manage the 'extra' info that vue and vuexfire create on state objects. I have an object mapped to a firebase reference called 'groups' which might contain zero or more 'group' records. Obviously with FB, you can't have a key with no value, so the key itself isn't even present when there are zero groups. In this case, the mapped vuexfire obejct looks like this:

    console.log(Reflect.ownKeys(state.groups))
    (3) [".value", ".key", "__ob__"]

If I then create a group called test, the result is as below:

    console.log(Reflect.ownKeys(state.groups))
    (3) ["test", ".key", "__ob__"]

So, calculating the number of groups is problematic (can't use `.length` of the Reflect call directly), and iterating using `v-for` is also tricky as it pulls out the vuexfire `.key` and `.value` properties if they're there (I'm presuming `.value` is only there if the reference is 'empty' as a placeholder? Or does it serve some other purpose?).

Do you have any advice or best ways of doing this with vuexfire? Or would you consider adding any helpers to vuexfire to make it easy to use mapped objects with `v-for`, count how many child nodes there are, etc.?

**Comment by posva** [comment]
Groups seems to be an array of groups, so just map it as an array 🙂 You'll then be able to use `.length`
`.value` is there when the value isn't an object, the same as vuefire. You can find more information about the format in its readme. I should probably add some notes to the readme here as well

**Comment by dsl101** [comment]
Erm - no, 'groups' is an object containing 'group's, and a 'group' is a record whose key is a unique name, and properties 'description', 'creator', 'creationDate', etc. The app starts from having no groups at all, and I'd like to make it not have to deal with special cases if possible.

**Comment by posva** [comment]
in fb everything is an object but you sometimes that object represents a list of things
