### ISSUE TITLE
Better place to use "query's"?

### ISSUE THREAD

**Issue by lgertel** [posva/vuexfire#69]
Hello!
I'm with a question about the best pratice when using vuexfire.

Where's the best place to put logic like this one:
```
        let appsRef = db.ref('applications')
        let connectorsRef = db.ref('connectors')
        let appConnectorsRef = appsRef.child(this.$route.params.id).child('connectors')
        appConnectorsRef.on('child_added', (snap) => {
          connectorsRef.child(snap.key).once('value', (snap) => {
            console.log(snap.val())
          })
        })
```

I have one application module that already used bindFirebaseRef to initialize data, and now I'm using this code inside a method component.

Not sure if this kind of thing should be added as a getter in my module or something like that.
Can you help me with this?

Ty!

**Comment by posva** [comment]
Refs should not be kept in the store state because they're complex objects, not state.
the `on`, then `once` part is relative to your app so it really depends on it, using it in a component's method may be enough 🙂
