### ISSUE TITLE
State management responsibilities

### ISSUE THREAD

**Issue by benjarwar** [posva/vuexfire#70]
I'm just starting to investigate Vuexfire, and trying to understand best implementation practices. In the example todo app, you're making [updates directly to Firebase references](https://github.com/posva/vuexfire/blob/master/examples/TodoApp/index.html#L61) from an app method. This strikes me as somewhat of an anti-pattern, since the whole idea of Vuex is to separate concerns, and manage state reactively by triggering actions/mutations on the store.

So it's almost like your Firebase db becomes a second/parallel state manager, and your Vuex store reacts to changes to the db, through which other collaborator Vue components can respond accordingly.

I'm wondering if, rather than triggering changes to Firebase from component methods, it would be better to create mutations/actions on the Vuex store that call Firebase reference methods. This would keep individual components agnostic to the database layer and put all state management responsibilities (including persisting changes to the database) in the Vuex layer.

Example:

```
// store.js
import Vue from 'vue';
import Vuex from 'vuex';
import { firebaseMutations, firebaseAction } from 'vuexfire';

Vue.use(Vuex);

const db = firebase.initializeApp(firebaseConfig).database();

const refs = {
  counter: db.ref('counter')
};

export default new Vuex.Store({
  state: {
    counter: {
      increment: 0
    }
  },
  getters: {
    counter (state) {
      return state.counter.increment;
    }
  },
  mutations: {
    increment (state) {
      refs.counter.set({
        increment: state.counter.increment + 1
      });
    },
    ...firebaseMutations
  },
  actions: {
    setCounterRef: firebaseAction(({bindFirebaseRef}, ref) => {
      bindFirebaseRef('counter', refs.counter);
    })
  }
});


// App.Vue
<template lang="pug">
  div.app
    button(v-on:click="increment") Increment
    span.counter {{ counter }}
</template>

<script>
import Vuex from 'vuex';

export default {
  methods: {
    increment () {
      this.$store.commit('increment');
    }
  },
  computed: {
    counter () {
      return this.$store.getters.counter;
    }
  }
}
</script>


// app.js
import App from './App.vue';
import store from './store.js';

new Vue({
  el: '#cohear',
  store,
  render: h => h(App),
  created() {
    this.$store.dispatch('setCounterRef');
  },
});
```

**Comment by posva** [comment]
yes, creating actions to modify the database is the way to go 🙂

**Comment by benjarwar** [comment]
Awesome, thanks for the reply... and for the library!

**Comment by quangv** [comment]
@posva thanks for the awesome library :)

> yes, creating actions to modify the database is the way to go 🙂

Would you say only modifying the db with actions for large app is best practice?
Or is VuexFire more neutral and doesn't prescribe a _"best"_ way to do things?

The example in the repo (as of `3.0.0-alpha.14`) has the Cloud Firestore db being modified inside the Vue components, which had me confused because I had thought best practice was for only Vuex actions should communicate with the API.

**Comment by posva** [comment]
only using actions is most of the time the best option because that way you can isolate Firebase interactions outside of components, making it much easier to test

**Comment by quangv** [comment]
Thanks Posva!
