### ISSUE TITLE
Stored Firebase reference converted to Observer on watch

### ISSUE THREAD

**Issue by benjarwar** [posva/vuexfire#71]
I'm attempting to watch the state of one of my Firebase references, in order to trigger subsequent actions. Getting unexpected behavior where an action, dispatched from a watch callback, can no longer find the Firebase reference's methods. Instead, the object in the the store, rather than being a Firebase reference, has become an Observer object. Is this expected? Am I somehow losing the context by trigger an action from a component's watch?

**Comment by posva** [comment]
Can you create a minimal repro using https://jsfiddle.net/posva/6w3ks04x/ so I can take a look? I'm not sure to understand it very well 🙂

**Comment by benjarwar** [comment]
Yeah, sorry, that explanation was not very clear in retrospect!

Here's as minimal as I can make it:

```
// firebase.js
import firebase from 'firebase';

const db = firebase.initializeApp(firebaseConfig).database();

const refs = {
  test: db.ref('test');
};

export { refs }


// actions.js
import { firebaseMutations, firebaseAction } from 'vuexfire';
import { refs } from './firebase';

export default {
  createReference (context) {
    context.commit('testRef', refs.test);
    context.dispatch('setTestReference', context.state.testRef);
  },

  setTestReference: firebaseAction(({ bindFirebaseRef }, ref) => {
    bindFirebaseRef('testRef', ref);
  }),

  fetchFromFirebase (context) {
    return context.state.testRef.once('value');
  },

  doSomethingWithData (context, data) {
    let transformedData;
    // transform the data, code redacted

    // this logs an Observer object instead of the Vuexfire-wrapped Firebase reference I expected
    console.log(context.state.testRef);

    // this fails with a TypeError: context.state.testRef.update is not a function
    context.state.testRef.update({
      new: transformedData
    });
  }
}


// mutations.js
export default {
  testRef (state, ref) {
    state.testRef = ref;
  }
}


// in App.vue
<script>
export default {
  methods: {
    start () {
      this.setReference();
      this.methodA();
    },

    setReference () {
      this.$store.dispatch('createReference');
    },

    methodA () {
      this.$store.dispatch('fetchFromFirebase')
          .then(this.methodB);
    },

    methodB (data) {
      // data is returned fine
      console.log(data.val());

      this.$store.dispatch('doSomethingWithData', data.val());
    }
}
</script>
```

So my architectural principles are like:
- Firebase database init and references happen in firebase.js
- Store Firebase references in Vuex via actions/mutations (I need to do this dynamically, because I'm creating new users, etc)
- Any changes to Firebase data, or data fetching, occur through actions

Everything above works in terms of setting up the Firebase ref, using the Vuexfire enhanced action to sync Vuex with Firebase, fetching the data via the `once` method. I'm guessing the issue is somewhere within the promise chaining, perhaps the `context` is getting garbled. But I need to do these types of operations often: fetch the data, `then` do something with the data, and persist new data via an action in a Promise callback.

Let me know if anything's unclear above.

**Comment by posva** [comment]
```js
context.commit('testRef', refs.test);
context.dispatch('setTestReference', context.state.testRef);
```

You're setting the testRef twice, so it may be that. I don't think you should save the ref on the state btw

You may also look up the `readyCallback` on the readme. That may be what you're looking for

**Comment by benjarwar** [comment]
So I think I may have had a fundamental misunderstanding of the library. I thought that storing the Firebase refs on the state first would allow setting Firebase data through Vuex. And that Vuexfire would then serve as a wrapper around that state-saved object, providing the bindings to Firebase.

I see now that it's more unidirectional. So flow is more like this:

1. Store the refs somewhere in your app
2. Set placeholders on the state for Vuexfire bindings
3. Instantiate Vuexfire using the refs and the placeholders on the state
4. To update Firebase data, trigger standard Firebase methods directly on the refs
5. To react to changed data, listen for changes to the Vuexfire-wrapped state objects

Is this correct?

**Comment by posva** [comment]
Yes 🙂
