### ISSUE TITLE
Question: firebaseAction, bindFirebaseRef for filtered data

### ISSUE THREAD

**Issue by lgertel** [posva/vuexfire#74]
Hello everyone!
Not sure how to do it, maybe it's a common question.

I have one Document called **applications** and another called **users**.
As it's now, my application store retrieves all applications on the node using:
```
setApplicationsRef: firebaseAction(({commit, bindFirebaseRef, state}, {ref}) => {
    return new Promise((resolve, reject) => {
      bindFirebaseRef('applications', ref, {
        readyCallback: (val) => {
          resolve(val)
        }
      })
    })
  })
```

The thing is that i want to retrieve only the applications that belongs to a user.
My documents:
```
applications
  -KkLUGf4jE1Q1pSSQgAR
     name: "app01"
     users
       fmHILzHN7BgecvFJR1Tttey2hHI3: true


users
  fmHILzHN7BgecvFJR1Tttey2hHI3
    applications
      -KkLUGf4jE1Q1pSSQgAR: true
    email: "lgertel@gmail.com"
    emailVerified: true
    name: "Lucas Gertel"
    photoUrl: "https://lh5.googleusercontent.com/-S7TveZd9tzM/..."
    uid: "fmHILzHN7BgecvFJR1Tttey2hHI3"

```

Thanks!

**Comment by posva** [comment]
Sorry, but this is only related to Firebase so I'll kindly ask you to search on Google or ask on StackOverflow. The guys at Firebase are usually open to answer this kind of questions, they have a lot of resources like a Youtube channel with really cool videos. You should checkout the Firebase for SQL developers. It may help you 🙂

**Comment by lgertel** [comment]
Great content, thanks.
