### ISSUE TITLE
Peer dependency issue?

### ISSUE THREAD

**Issue by dsl101** [posva/vuexfire#76]
I just tried to add `vuexfire` to an existing project, and I get this:

    npm ERR! peer dep missing: firebase@^2.4.1 || 3.x.x, required by vuexfire@2.1.2

Is vuexfire not compatible with firebase@4.0.0? Or is it just a transient thing whilst stuff gets updated?

**Comment by posva** [comment]
It does work 😄 
I just released a new version. Thanks for letting me know
