### ISSUE TITLE
How to get feedback when database is loading?

### ISSUE THREAD

**Issue by alewiahmed** [posva/vuexfire#86]
I like vuexfire very much. What I wanted was to have a loading gif show when the database is waiting to be loaded. I tried using the readyCallback but it is not working. When the store is loaded, it doesn't call the readyCallback function. what am I missing.

**Comment by posva** [comment]
hey, glad you like it. You may be doing something wrong, here's a working example: https://jsfiddle.net/p6pcpxx4/
if you find a bug, please open a new issue with a repro 😉

**Comment by alewiahmed** [comment]
Thanx @posva. you're right, I was doing something wrong. Your solution is spot on.
