### ISSUE TITLE
VUEXFIRE_ARRAY_INITIALIZE replace Saver Side Rendering array status.

### ISSUE THREAD

**Issue by k2wanko** [posva/vuexfire#87]
VUEXFIRE_ARRAY_INITIALIZE replace Saver Side Rendering array status.
Because of that, the rendering result disappears once.
I do not want to initialize the array.

https://github.com/posva/vuexfire/blob/master/src/utils/mutations.js#L16

**Comment by posva** [comment]
Hey, thanks for raising this. The way I want to fix it is by waiting before setting the array if the array has already some content. I inted to add this feature, because it also allows to rebind arrays (eg: pagination).

**Comment by posva** [comment]
I'm wondering if I should make wait: true the default

**Comment by posva** [comment]
I made it the default because it makes things easier in most cases
