### ISSUE TITLE
Question / Clarification

### ISSUE THREAD

**Issue by chancet1982** [posva/vuexfire#92]
"noob" alert. 

I seem to have a hard time understanding some things about vuexfire. For example: why is the firebase binding preferable compared to using Firebase's realtime database API directly in conjunction with Vuex? Isnt it possible to simply use `dbRef.set(dataObject);` for setting objects in firebase and then "observing" these changes in realtime using `dbRef.on('value', data => doSomeAction(data));` for committing the mutations to the state? 

Secondly, I think the topic of the firebaseMutations is confusing. According to the documentation:
> This object contains VuexFire internal mutations. They are all prefixed by vuexfire/. This object must be added in the root Store mutations object.
Does that mean that firebaseMutations are vuexFire **internal ref only** I.E. should never be touched? or should these be defined somehow? if so please how?

Third Question, bindFirebaseRef, why are we doing it? am I right to assume that by doing this we can update the state variable directly whenever the database updates instead of using mutations?

additionally, if I understand correctly, bindFirebaseRef binds a state variable to firebase's database reference. If so, should this binding be added per database reference? **should this binding be added once(per store) or whenever the database is manipulated?** Does it actually matter if it is implemented as an action?

Last question: if I understand correctly, a firebaseAction is should be considered as an "enhanced action" which exposes two additional parameters in the context, bindFirebaseRef and unbindFirebaseRef.
Is that the case? If that is the case using an action to addATodo should look something like:
`addTodo: firebaseAction(({ bindFirebaseRef }, { ref }) => {
  ref.push(this.newMalt);
  bindFirebaseRef('availableMalts', ref) //not sure if we need to "rebind" the state or not...
}),`
The documentation is not really clear about this TBH 
> In order to use VuexFire, you have to enhance actions. This action enhancer takes the actual action and enhances it with two additional parameters in the context, bindFirebaseRef and unbindFirebaseRef:

@posva, I confess: I don't really get the documentation. I've read it several times but im still confused. I think it would really help if the online demo will to take advantage of store actions for database manipulation? (addTodo, removeTodo, updateTodo)

**Comment by posva** [comment]
> why is the firebase binding preferable compared to using Firebase's realtime database API directly

It does all the boilerplate for you

`firebaseMutations` are internal mutations are should probably never be used

`bindFirebaseRef` _binds_ a ref to the a property on the state. It setup all the listeners so the information is kept up to date

> additionally, if I understand correctly, bindFirebaseRef binds a state variable to firebase's database reference

No, it's the other way around

There's no need to rebind anything once it's bound

> I confess: I don't really get the documentation. I've read it several times but im still confused. I think it would really help if the online demo will to take advantage of store actions for database manipulation? (addTodo, removeTodo, updateTodo)

I kept the demo super simple on purporse because I want users to feel free about how and where to handle the updates.

I need to find the time for more documentation see #28
