### ISSUE TITLE
Can't build using rollup

### ISSUE THREAD

**Issue by paulopmx** [posva/vuexfire#96]
I keep getting this error:
Error: 'firebaseMutations' is not exported by node_modules/vuexfire/dist/vuexfire.js

But if I rename vuexfire.esm.js to vuexfire.js, rollup would work.

**Comment by posva** [comment]
just do `import { firebaseMutations } from 'vuexfire'`
That will use the `vuexfire.esm.js` which is the valid one for es6 imports
`vuexfire.js` is for CDN

**Comment by paulopmx** [comment]
I did and I am.
I am using rollup and buble to compile the code. Please read open ticket.
Paulo P. Mariñas Code Ninja https://codeninja.co
On Sat, Aug 12, 2017 at 12:17 AM, Eduardo San Martin Morote <notifications@github.com> wrote:
just do import { firebaseMutations } from 'vuexfire'
That will use the vuexfire.esm.js which is the valid one for es6 imports
vuexfire.js is for CDN

**Comment by posva** [comment]
> Error: 'firebaseMutations' is not exported by node_modules/vuexfire/dist/vuexfire.js

If you get that error you're not importing from the right file. You can force the import of the `esm` file with `import { firebaseMutations } from 'vuexfire/dist/vuexfire.esm'`

**Comment by paulopmx** [comment]
@posva that work thanks. I'm still new at es6 stuff.

Wouldn't it help other users of rollup and your plugin, to find out why rollup and node-resolve is getting confused while it doesn't in other 3rd party libs?

Anyway thanks again.

**Comment by posva** [comment]
Sure, if you find more info, make sure to pinng me 😉
